[colors]
black        = "282c34"
white        = "abb2bf"
light_red    = "e06c75"
dark_red     = "be5046"
green        = "98c379"
light_yellow = "e5c075"
dark_yellow  = "d19a66"
blue         = "61afef"
magenta      = "c678dd"
cyan         = "56b6c2"
gutter_gray  = "4b5263"
comment_gray = "5c6370"

[syntax]
strings = "green"
numbers = "dark_yellow"
keywords = "light_red"
types = "light_yellow"
macros = "magenta"
operators = "magenta"
functions = "blue"
methods = "blue"
comments = "comment_gray"
text = "white"

[ui]
foreground = "white"
background = "black"
unfocused_text = "gutter_gray"
current_line = "gutter_gray"
cursor = "blue"
